site_name: RxNet
site_url: https://mousebrilliant.github.io/RxNet
repo_name: MouseBrilliant/RxNet
repo_url: https://github.com/MouseBrilliant/RxNet
theme:
  name: material
  palette:
    primary: red
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.footnote.tooltips
plugins:
  - search
  - offline
  - minify_html:
      do_not_minify_doctype: true
      ensure_spec_compliant_unquoted_attribute_values: true
      keep_closing_tags: false
      keep_html_and_head_opening_tags: false
      keep_spaces_between_attributes: true
      keep_comments: false
      keep_input_type_text_attr: true
      keep_ssi_comments: false
      preserve_brace_template_syntax: false
      preserve_chevron_percent_template_syntax: false
      minify_css: true
      minify_js: true
      remove_bangs: false
      remove_processing_instructions: false
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg