site_name: RxNet
site_url: https://mousebrilliant.github.io/RxNet
repo_name: MouseBrilliant/RxNet
repo_url: https://github.com/MouseBrilliant/RxNet
theme:
  name: material
  palette:
    primary: red
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.footnote.tooltips
plugins:
  - search
  - offline
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg